### ISSUE TITLE
Consul registration doesn't create, does update.

### ISSUE THREAD

**Issue by dschutterop** [catwithboots/SQLServerConsul#2]
It looks like the SP updates consul entries just fine, but doesn't create entries when they don't exist.

I found a number of errors corresponding to the date/time I'm trying to register DB's:
```2018/03/10 13:34:02 [ERR] http: Request PUT /v1/agent/check/pass/service:xdlogging-db?note=Updated%20by%20SQLServerConsul, error: CheckID does not have associated TTL from=127.0.0.1:56062```

When I use the testGUI to 'manually' register the databases in consul, they get created just fine, while subsequent SP runs update the entries without any problem.

**Comment by rmul** [comment]
I'll see if I can reproduce, @dschutterop which version of consul/sql server and this library are you using?

**Comment by dschutterop** [comment]
Currently running on:
 - Windows 2012 R2
 - SQL server 2014
 - SQLServerConsul assembly 1.1.0.0
 - Consul assembly 0.7.0.2

The manual fix that I ran with the GUI tool has the following versions:
 - Consul.dll 0.7.0.2
 - SQLServerConsul.dll 1.0.0.0
 - SQLServerConsulTestGui.exe 1.0.0.0

**Comment by rmul** [comment]
fixed and uploaded new dbasst.1.1.2.zip to your repo

**Comment by dschutterop** [comment]
Thanks!
